version: '3.8'

services:
  cookbook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cookbook
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cookbook_user
      - MYSQL_PASSWORD=cookbook_password
    ports:
      - "3306:3306"

volumes:
  mysql_data:
